/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class UnorderedSet {
  constructor()
  insert(value: string): void
  has(value: string): boolean
  iterate(): Array<string>
}
